### PR TITLE
Test first for end of object to not print a superflous ...

### PR DESCRIPTION
**Pull request by kpoeck**
Fixes ansi-tests:
* PRINT.ARRAY.LENGTH.2
* PRINT.ARRAY.LENGTH.4
* PRINT.ARRAY.LENGTH.7
* PRINT-LEVEL.8
* PRINT-LEVEL.9

running complete ansi-tests show no new regression.

Running ccl-tests shows no regressions:
```lisp
karsten-poecks-macbook-pro:ccl-tests karstenpoeck$ ../ccl-git-karsten/dx86cl64 -n -l load.lisp
Clozure Common Lisp Version 1.12-dev (v1.12-dev.3-89-gf5c30785) DarwinX8664

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (run-tests)
Doing 21904 pending tests of 21904 tests total.
Invoking restart: #<RESTART CL-TEST::FOO #x133C12D>
Invoking restart: #<RESTART CL-TEST::FOO #x133C12D>
Invoking restart: #<RESTART CL-TEST::FOO #x133C12D>
Invoking restart: #<RESTART CL-TEST::FOO #x133C12D>
Invoking restart: #<RESTART CL-TEST::FOO #x133C12D>

=============== All tests succeeded ===============

(FUNCALL DO-TESTS :COMPILE COMPILE :VERBOSE VERBOSE :CATCH-ERRORS T)
took 153,454,653 microseconds (153.454650 seconds) to run.
       2,381,189 microseconds (  2.381189 seconds, 1.55%) of which was spent in GC.
During that period, and with 8 available CPU cores,
     143,693,740 microseconds (143.693740 seconds) were spent in user mode
       9,652,434 microseconds (  9.652434 seconds) were spent in system mode
 7,716,908,256 bytes of memory allocated.
 22,521 minor page faults, 0 major page faults, 0 swaps.
NIL
````

### CODE REVIEW

**Comment by phoe** [comment]
I think it would maybe be good to coordinate work if we're about to work on separately fixing the same bugs in CCL!

https://github.com/phoe-trash/ccl/commit/48e542cb19d12a7d8e84526d7627677de2d88987

**Comment by kpoeck** [comment]
Bright idea, open to proposals

**Comment by kpoeck** [comment]
Now also fixed:
* PRINT.ARRAY.LENGTH.1
* PRINT.ARRAY.LENGTH.3

**Comment by kpoeck** [comment]
Unfortunately I did the same work as phoe, and I should not repeat that in order not to misinvest our mutual time.

As a first I idea - open for comments - we could report the issues we are working on as an issue and announce that we would work on them.

@phoe , your opinion

**Comment by phoe** [comment]
@kpoeck Sounds good! These bugs are simple, so fixes weren't hard, so not much time was misinvested.

I am fixing tests on my own fork at https://github.com/phoe-trash/ccl and I use the mainstream fork of ansi-tests instead of the CCL one. I use Travis for checking that the build passes and which tests still fail.

Example run that is fresh at the time of writing this: https://travis-ci.com/phoe-trash/ccl/jobs/260364969

My branch is 30 commits ahead of ccl/master so far - should I make a (big) PR to synchronize better?

**Comment by kpoeck** [comment]
I assume smaller PRs are better, but thats probably for @xrme to decide.

Regarding this specific PR, please advise on how to proceed, e,g, I could close it (so that we take your code) or ask @XRME to review it in its present state

Please decide (I will go with your decision, no questions asked)

**Comment by phoe** [comment]
Please go forwards with your PR. You're the first to submit it. (:

**Comment by kpoeck** [comment]
ok, than @xrme , please check

**Pull request merged**
